namespace UserAuthService.Templates
{
    public enum EmailType
    {
        Welcome = 0,
        OTP = 1,
        Notification = 2,
        ApplicationStatus = 3,
        LoginDetail = 4,
    }
    public class EmailTemplate
    {
        public string GetHTMLTemplate(EmailType emailType)
        {
            switch (emailType)
            {
                case EmailType.Welcome:
                    return WelcomeEmail();
                case EmailType.OTP:
                    return OTPMessage();
                case EmailType.Notification:
                    return NotificationMessage();
                case EmailType.LoginDetail:
                    return LoginDetailsEmail();
                default:
                    return "";
            }


        }
        private string WelcomeEmail()
        {
            return
                   @"<!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.0 Transitional//EN"" ""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd""><html dir=""ltr"" xmlns=""http://www.w3.org/1999/xhtml"" xmlns:o=""urn:schemas-microsoft-com:office:office"" lang=""en""><head><meta charset=""UTF-8""><meta content=""width=device-width, initial-scale=1"" name=""viewport""><meta name=""x-apple-disable-message-reformatting""><meta http-equiv=""X-UA-Compatible"" content=""IE=edge""><meta content=""telephone=no"" name=""format-detection""><title>New Message 2</title> <!--[if (mso 16)]><style type=""text/css"">     a {text-decoration: none;}     </style><![endif]--> <!--[if gte mso 9]><style>sup { font-size: 100% !important; }</style><![endif]--> <!--[if gte mso 9]><noscript> <xml> <o:OfficeDocumentSettings> <o:AllowPNG></o:AllowPNG> <o:PixelsPerInch>96</o:PixelsPerInch> </o:OfficeDocumentSettings> </xml> </noscript>
<![endif]--><style type=""text/css"">.rollover:hover .rollover-first { max-height:0px!important; display:none!important;}.rollover:hover .rollover-second { max-height:none!important; display:block!important;}.rollover span { font-size:0px;}u + .body img ~ div div { display:none;}#outlook a { padding:0;}span.MsoHyperlink,span.MsoHyperlinkFollowed { color:inherit; mso-style-priority:99;}a.es-button { mso-style-priority:100!important; text-decoration:none!important;}a[x-apple-data-detectors],#MessageViewBody a { color:inherit!important; text-decoration:none!important; font-size:inherit!important; font-family:inherit!important; font-weight:inherit!important; line-height:inherit!important;}.es-desk-hidden { display:none; float:left; overflow:hidden; width:0; max-height:0; line-height:0; mso-hide:all;} @media only screen and (max-width:600px) {.es-m-p0r { padding-right:0px!important } .es-p-default { }
 *[class=""gmail-fix""] { display:none!important } p, a { line-height:150%!important } h1, h1 a { line-height:120%!important } h2, h2 a { line-height:120%!important } h3, h3 a { line-height:120%!important } h4, h4 a { line-height:120%!important } h5, h5 a { line-height:120%!important } h6, h6 a { line-height:120%!important } .es-header-body p { } .es-content-body p { } .es-footer-body p { } .es-infoblock p { } h1 { font-size:36px!important; text-align:left } h2 { font-size:26px!important; text-align:left } h3 { font-size:20px!important; text-align:left } h4 { font-size:24px!important; text-align:left } h5 { font-size:20px!important; text-align:left } h6 { font-size:16px!important; text-align:left } .es-header-body h1 a, .es-content-body h1 a, .es-footer-body h1 a { font-size:36px!important } .es-header-body h2 a, .es-content-body h2 a, .es-footer-body h2 a { font-size:26px!important }
 .es-header-body h3 a, .es-content-body h3 a, .es-footer-body h3 a { font-size:20px!important } .es-header-body h4 a, .es-content-body h4 a, .es-footer-body h4 a { font-size:24px!important } .es-header-body h5 a, .es-content-body h5 a, .es-footer-body h5 a { font-size:20px!important } .es-header-body h6 a, .es-content-body h6 a, .es-footer-body h6 a { font-size:16px!important } .es-menu td a { font-size:12px!important } .es-header-body p, .es-header-body a { font-size:14px!important } .es-content-body p, .es-content-body a { font-size:14px!important } .es-footer-body p, .es-footer-body a { font-size:14px!important } .es-infoblock p, .es-infoblock a { font-size:12px!important } .es-m-txt-c, .es-m-txt-c h1, .es-m-txt-c h2, .es-m-txt-c h3, .es-m-txt-c h4, .es-m-txt-c h5, .es-m-txt-c h6 { text-align:center!important }
 .es-m-txt-r, .es-m-txt-r h1, .es-m-txt-r h2, .es-m-txt-r h3, .es-m-txt-r h4, .es-m-txt-r h5, .es-m-txt-r h6 { text-align:right!important } .es-m-txt-j, .es-m-txt-j h1, .es-m-txt-j h2, .es-m-txt-j h3, .es-m-txt-j h4, .es-m-txt-j h5, .es-m-txt-j h6 { text-align:justify!important } .es-m-txt-l, .es-m-txt-l h1, .es-m-txt-l h2, .es-m-txt-l h3, .es-m-txt-l h4, .es-m-txt-l h5, .es-m-txt-l h6 { text-align:left!important } .es-m-txt-r img, .es-m-txt-c img, .es-m-txt-l img { display:inline!important } .es-m-txt-r .rollover:hover .rollover-second, .es-m-txt-c .rollover:hover .rollover-second, .es-m-txt-l .rollover:hover .rollover-second { display:inline!important } .es-m-txt-r .rollover span, .es-m-txt-c .rollover span, .es-m-txt-l .rollover span { line-height:0!important; font-size:0!important; display:block } .es-spacer { display:inline-table }
 a.es-button, button.es-button { font-size:20px!important; padding:10px 20px 10px 20px!important; line-height:120%!important } a.es-button, button.es-button, .es-button-border { display:inline-block!important } .es-m-fw, .es-m-fw.es-fw, .es-m-fw .es-button { display:block!important } .es-m-il, .es-m-il .es-button, .es-social, .es-social td, .es-menu { display:inline-block!important } .es-adaptive table, .es-left, .es-right { width:100%!important } .es-content table, .es-header table, .es-footer table, .es-content, .es-footer, .es-header { width:100%!important; max-width:600px!important } .adapt-img { width:100%!important; height:auto!important } .es-mobile-hidden, .es-hidden { display:none!important } .es-desk-hidden { width:auto!important; overflow:visible!important; float:none!important; max-height:inherit!important; line-height:inherit!important } tr.es-desk-hidden { display:table-row!important }
 table.es-desk-hidden { display:table!important } td.es-desk-menu-hidden { display:table-cell!important } .es-menu td { width:1%!important } table.es-table-not-adapt, .esd-block-html table { width:auto!important } .h-auto { height:auto!important } }@media screen and (max-width:384px) {.mail-message-content { width:414px!important } }</style>
 </head> <body class=""body"" style=""width:100%;height:100%;padding:0;Margin:0""><div dir=""ltr"" class=""es-wrapper-color"" lang=""en"" style=""background-color:#FAFAFA""> <!--[if gte mso 9]><v:background xmlns:v=""urn:schemas-microsoft-com:vml"" fill=""t""> <v:fill type=""tile"" color=""#fafafa""></v:fill> </v:background><![endif]--><table width=""100%"" cellspacing=""0"" cellpadding=""0"" class=""es-wrapper"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;padding:0;Margin:0;width:100%;height:100%;background-repeat:repeat;background-position:center top;background-color:#FAFAFA""><tr>
<td valign=""top"" style=""padding:0;Margin:0""><table cellpadding=""0"" cellspacing=""0"" align=""center"" class=""es-header"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important;background-color:transparent;background-repeat:repeat;background-position:center top""><tr><td align=""center"" style=""padding:0;Margin:0""><table bgcolor=""#ffffff"" align=""center"" cellpadding=""0"" cellspacing=""0"" class=""es-header-body"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:600px""><tr><td align=""left"" style=""Margin:0;padding-top:10px;padding-right:20px;padding-bottom:10px;padding-left:20px""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr>
<td valign=""top"" align=""center"" class=""es-m-p0r"" style=""padding:0;Margin:0;width:560px""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr><td align=""center"" style=""padding:0;Margin:0;padding-bottom:20px;font-size:0px""><img src=""https://eovwsew.stripocdn.email/content/guids/CABINET_01a3b21ebaa00abfcaf2f1678a33a1182b7105afe5bd44d98561066f5c8352e9/images/thootologo_1.png"" href=""https://thooto.com/#"" alt="""" width=""175"" title=""Logo"" class=""adapt-img"" style=""display:block;font-size:12px;border:0;outline:none;text-decoration:none""></td> </tr></table></td></tr></table></td></tr></table></td></tr></table> <table cellpadding=""0"" cellspacing=""0"" align=""center"" class=""es-content"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important""><tr>
<td align=""center"" style=""padding:0;Margin:0""><table bgcolor=""#ffffff"" align=""center"" cellpadding=""0"" cellspacing=""0"" class=""es-content-body"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FFFFFF;width:600px""><tr><td align=""left"" style=""padding:0;Margin:0;padding-right:20px;padding-left:20px;padding-top:15px""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr><td align=""center"" valign=""top"" style=""padding:0;Margin:0;width:560px""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr>
<td align=""center"" class=""es-m-txt-c"" style=""padding:0;Margin:0;padding-top:15px;padding-bottom:15px""><h1 style=""Margin:0;font-family:arial, 'helvetica neue', helvetica, sans-serif;mso-line-height-rule:exactly;letter-spacing:0;font-size:46px;font-style:normal;font-weight:bold;line-height:55.2px;color:#333333"">Thanks for joining us!</h1> </td></tr><tr><td align=""left"" style=""padding:0;Margin:0;padding-top:10px;padding-bottom:10px""><p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px"">We're excited to have you here. Explore our platform and discover how we can help you achieve your goals. Whether you're looking to learn, teach, or manage, thooto is here to support you every step of the way. Let's get started!</p></td></tr></table></td></tr></table></td></tr> <tr>
<td align=""left"" style=""padding:0;Margin:0;padding-right:20px;padding-bottom:10px;padding-left:20px""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr><td align=""center"" valign=""top"" style=""padding:0;Margin:0;width:560px""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:separate;border-spacing:0px;border-radius:5px"" role=""presentation""><tr>
<td align=""left"" style=""padding:0;Margin:0;padding-bottom:10px;padding-top:20px""><p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;letter-spacing:0;color:#333333;font-size:14px""><strong>Got a question?</strong><br>Email us at <a href=""mailto:account@fraktionaldev.com"" style=""mso-line-height-rule:exactly;text-decoration:underline;color:#5C68E2;font-size:14px"">account@fraktionaldev.com</a> or give us a call at&nbsp; +27 10 900 5173.</p> <p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;letter-spacing:0;color:#333333;font-size:14px"">Thanks,<br>The thooto Team</p></td></tr></table></td></tr></table></td></tr></table></td></tr></table>
 <table cellpadding=""0"" cellspacing=""0"" align=""center"" class=""es-footer"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important;background-color:transparent;background-repeat:repeat;background-position:center top""><tr><td align=""center"" style=""padding:0;Margin:0""><table cellspacing=""0"" align=""center"" cellpadding=""0"" class=""es-footer-body"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:600px"" role=""none""><tr><td align=""left"" style=""Margin:0;padding-right:20px;padding-left:20px;padding-bottom:20px;padding-top:20px""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr>
<td align=""left"" style=""padding:0;Margin:0;width:560px""><table cellspacing=""0"" width=""100%"" cellpadding=""0"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr><td align=""center"" style=""padding:0;Margin:0;padding-top:15px;padding-bottom:15px;font-size:0""><table cellpadding=""0"" cellspacing=""0"" class=""es-table-not-adapt es-social"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr>
<td align=""center"" valign=""top"" style=""padding:0;Margin:0;padding-right:40px""><a target=""_blank"" href=""https://www.linkedin.com/company/thooto/posts/?feedView=all"" style=""mso-line-height-rule:exactly;text-decoration:underline;color:#333333;font-size:12px""><img alt=""In"" width=""32"" height=""32"" title=""LinkedIn"" src=""https://eovwsew.stripocdn.email/content/assets/img/social-icons/logo-black/linkedin-logo-black.png"" style=""display:block;font-size:14px;border:0;outline:none;text-decoration:none""></a> </td></tr></table></td></tr><tr><td align=""center"" style=""padding:0;Margin:0;padding-bottom:35px""><p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:18px;letter-spacing:0;color:#333333;font-size:12px"">thooto (2024). All Rights Reserved.</p>
<p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:18px;letter-spacing:0;color:#333333;font-size:12px"">Corner Tyrwhitt and 24 Cradock Ave, Rosebank, Johannesburg, 2196</p><p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:18px;letter-spacing:0;color:#333333;font-size:12px"">Call: +27 10 900 5173</p></td></tr> <tr><td style=""padding:0;Margin:0""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" class=""es-menu"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr class=""links"">
<td width=""33.33%"" align=""center"" valign=""top"" style=""Margin:0;border:0;padding-top:5px;padding-bottom:5px;padding-right:5px;padding-left:5px""><a target=""_blank"" href=""https://thooto.com"" style=""mso-line-height-rule:exactly;text-decoration:none;font-family:arial, 'helvetica neue', helvetica, sans-serif;display:block;color:#999999;font-size:12px"">Visit Us </a></td> <td align=""center"" valign=""top"" width=""33.33%"" style=""Margin:0;border:0;padding-top:5px;padding-bottom:5px;padding-right:5px;padding-left:5px;border-left:1px solid #cccccc""><a target=""_blank"" href="""" style=""mso-line-height-rule:exactly;text-decoration:none;font-family:arial, 'helvetica neue', helvetica, sans-serif;display:block;color:#999999;font-size:12px"">Privacy Policy</a></td>
<td align=""center"" valign=""top"" width=""33.33%"" style=""Margin:0;border:0;padding-top:5px;padding-bottom:5px;padding-right:5px;padding-left:5px;border-left:1px solid #cccccc""><a target=""_blank"" href="""" style=""mso-line-height-rule:exactly;text-decoration:none;font-family:arial, 'helvetica neue', helvetica, sans-serif;display:block;color:#999999;font-size:12px"">Terms of Use</a></td></tr></table></td></tr></table></td></tr></table></td></tr></table></td></tr></table> <table cellpadding=""0"" cellspacing=""0"" align=""center"" class=""es-content"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important""><tr>
<td align=""center"" class=""es-info-area"" style=""padding:0;Margin:0""><table bgcolor=""#FFFFFF"" align=""center"" cellpadding=""0"" cellspacing=""0"" class=""es-content-body"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:600px"" role=""none""><tr><td align=""left"" style=""padding:20px;Margin:0""><table width=""100%"" cellpadding=""0"" cellspacing=""0"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr><td align=""center"" valign=""top"" style=""padding:0;Margin:0;width:560px""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr>
<td align=""center"" class=""es-infoblock"" style=""padding:0;Margin:0""><p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:18px;letter-spacing:0;color:#CCCCCC;font-size:12px""><a target=""_blank"" href="""" style=""mso-line-height-rule:exactly;text-decoration:underline;color:#CCCCCC;font-size:12px""></a>No longer want to receive these emails?&nbsp;<a href="""" target=""_blank"" style=""mso-line-height-rule:exactly;text-decoration:underline;color:#CCCCCC;font-size:12px"">Unsubscribe</a>.<a target=""_blank"" href="""" style=""mso-line-height-rule:exactly;text-decoration:underline;color:#CCCCCC;font-size:12px""></a></p> </td></tr></table></td></tr></table></td></tr></table></td></tr></table></td></tr></table></div></body></html>";
        }


        private string OTPMessage()
        {
            return @"<!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.0 Transitional//EN"" ""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd""><html dir=""ltr"" xmlns=""http://www.w3.org/1999/xhtml"" xmlns:o=""urn:schemas-microsoft-com:office:office"" lang=""en""><head><meta charset=""UTF-8""><meta content=""width=device-width, initial-scale=1"" name=""viewport""><meta name=""x-apple-disable-message-reformatting""><meta http-equiv=""X-UA-Compatible"" content=""IE=edge""><meta content=""telephone=no"" name=""format-detection""><title>New Message 4</title> <!--[if (mso 16)]><style type=""text/css"">     a {text-decoration: none;}     </style><![endif]--> <!--[if gte mso 9]><style>sup { font-size: 100% !important; }</style><![endif]--> <!--[if gte mso 9]><noscript> <xml> <o:OfficeDocumentSettings> <o:AllowPNG></o:AllowPNG> <o:PixelsPerInch>96</o:PixelsPerInch> </o:OfficeDocumentSettings> </xml> </noscript>
<![endif]--><style type=""text/css"">.rollover:hover .rollover-first { max-height:0px!important; display:none!important;}.rollover:hover .rollover-second { max-height:none!important; display:block!important;}.rollover span { font-size:0px;}u + .body img ~ div div { display:none;}#outlook a { padding:0;}span.MsoHyperlink,span.MsoHyperlinkFollowed { color:inherit; mso-style-priority:99;}a.es-button { mso-style-priority:100!important; text-decoration:none!important;}a[x-apple-data-detectors],#MessageViewBody a { color:inherit!important; text-decoration:none!important; font-size:inherit!important; font-family:inherit!important; font-weight:inherit!important; line-height:inherit!important;}.es-desk-hidden { display:none; float:left; overflow:hidden; width:0; max-height:0; line-height:0; mso-hide:all;} @media only screen and (max-width:600px) {.es-m-p0r { padding-right:0px!important } .es-m-p0l { padding-left:0px!important } .es-p-default { }
 *[class=""gmail-fix""] { display:none!important } p, a { line-height:150%!important } h1, h1 a { line-height:120%!important } h2, h2 a { line-height:120%!important } h3, h3 a { line-height:120%!important } h4, h4 a { line-height:120%!important } h5, h5 a { line-height:120%!important } h6, h6 a { line-height:120%!important } .es-header-body p { } .es-content-body p { } .es-footer-body p { } .es-infoblock p { } h1 { font-size:36px!important; text-align:left } h2 { font-size:26px!important; text-align:left } h3 { font-size:20px!important; text-align:left } h4 { font-size:24px!important; text-align:left } h5 { font-size:20px!important; text-align:left } h6 { font-size:16px!important; text-align:left } .es-header-body h1 a, .es-content-body h1 a, .es-footer-body h1 a { font-size:36px!important } .es-header-body h2 a, .es-content-body h2 a, .es-footer-body h2 a { font-size:26px!important }
 .es-header-body h3 a, .es-content-body h3 a, .es-footer-body h3 a { font-size:20px!important } .es-header-body h4 a, .es-content-body h4 a, .es-footer-body h4 a { font-size:24px!important } .es-header-body h5 a, .es-content-body h5 a, .es-footer-body h5 a { font-size:20px!important } .es-header-body h6 a, .es-content-body h6 a, .es-footer-body h6 a { font-size:16px!important } .es-menu td a { font-size:12px!important } .es-header-body p, .es-header-body a { font-size:14px!important } .es-content-body p, .es-content-body a { font-size:16px!important } .es-footer-body p, .es-footer-body a { font-size:14px!important } .es-infoblock p, .es-infoblock a { font-size:12px!important } .es-m-txt-c, .es-m-txt-c h1, .es-m-txt-c h2, .es-m-txt-c h3, .es-m-txt-c h4, .es-m-txt-c h5, .es-m-txt-c h6 { text-align:center!important }
 .es-m-txt-r, .es-m-txt-r h1, .es-m-txt-r h2, .es-m-txt-r h3, .es-m-txt-r h4, .es-m-txt-r h5, .es-m-txt-r h6 { text-align:right!important } .es-m-txt-j, .es-m-txt-j h1, .es-m-txt-j h2, .es-m-txt-j h3, .es-m-txt-j h4, .es-m-txt-j h5, .es-m-txt-j h6 { text-align:justify!important } .es-m-txt-l, .es-m-txt-l h1, .es-m-txt-l h2, .es-m-txt-l h3, .es-m-txt-l h4, .es-m-txt-l h5, .es-m-txt-l h6 { text-align:left!important } .es-m-txt-r img, .es-m-txt-c img, .es-m-txt-l img { display:inline!important } .es-m-txt-r .rollover:hover .rollover-second, .es-m-txt-c .rollover:hover .rollover-second, .es-m-txt-l .rollover:hover .rollover-second { display:inline!important } .es-m-txt-r .rollover span, .es-m-txt-c .rollover span, .es-m-txt-l .rollover span { line-height:0!important; font-size:0!important; display:block } .es-spacer { display:inline-table }
 a.es-button, button.es-button { font-size:20px!important; padding:10px 20px 10px 20px!important; line-height:120%!important } a.es-button, button.es-button, .es-button-border { display:inline-block!important } .es-m-fw, .es-m-fw.es-fw, .es-m-fw .es-button { display:block!important } .es-m-il, .es-m-il .es-button, .es-social, .es-social td, .es-menu { display:inline-block!important } .es-adaptive table, .es-left, .es-right { width:100%!important } .es-content table, .es-header table, .es-footer table, .es-content, .es-footer, .es-header { width:100%!important; max-width:600px!important } .adapt-img { width:100%!important; height:auto!important } .es-mobile-hidden, .es-hidden { display:none!important } .es-desk-hidden { width:auto!important; overflow:visible!important; float:none!important; max-height:inherit!important; line-height:inherit!important } tr.es-desk-hidden { display:table-row!important }
 table.es-desk-hidden { display:table!important } td.es-desk-menu-hidden { display:table-cell!important } .es-menu td { width:1%!important } table.es-table-not-adapt, .esd-block-html table { width:auto!important } .h-auto { height:auto!important } }@media screen and (max-width:384px) {.mail-message-content { width:414px!important } }</style>
 </head> <body class=""body"" style=""width:100%;height:100%;padding:0;Margin:0""><div dir=""ltr"" class=""es-wrapper-color"" lang=""en"" style=""background-color:#FAFAFA""> <!--[if gte mso 9]><v:background xmlns:v=""urn:schemas-microsoft-com:vml"" fill=""t""> <v:fill type=""tile"" color=""#fafafa""></v:fill> </v:background><![endif]--><table width=""100%"" cellspacing=""0"" cellpadding=""0"" class=""es-wrapper"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;padding:0;Margin:0;width:100%;height:100%;background-repeat:repeat;background-position:center top;background-color:#FAFAFA""><tr><td valign=""top"" style=""padding:0;Margin:0""><table cellpadding=""0"" cellspacing=""0"" align=""center"" class=""es-content"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important""><tr>
<td align=""center"" class=""es-info-area"" style=""padding:0;Margin:0""><table align=""center"" cellpadding=""0"" cellspacing=""0"" bgcolor=""#FFFFFF"" class=""es-content-body"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:600px"" role=""none""><tr><td align=""left"" style=""padding:20px;Margin:0""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr><td align=""center"" valign=""top"" style=""padding:0;Margin:0;width:560px""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr>
<td align=""center"" class=""es-infoblock"" style=""padding:0;Margin:0""><p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:18px;letter-spacing:0;color:#CCCCCC;font-size:12px""></p> </td></tr></table></td></tr></table></td></tr></table></td></tr></table> <table cellpadding=""0"" cellspacing=""0"" align=""center"" class=""es-header"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important;background-color:transparent;background-repeat:repeat;background-position:center top""><tr>
<td align=""center"" style=""padding:0;Margin:0""><table bgcolor=""#ffffff"" align=""center"" cellpadding=""0"" cellspacing=""0"" class=""es-header-body"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:600px""><tr><td align=""left"" style=""Margin:0;padding-top:10px;padding-right:20px;padding-bottom:10px;padding-left:20px""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr><td valign=""top"" align=""center"" class=""es-m-p0r"" style=""padding:0;Margin:0;width:560px""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr>
<td align=""center"" style=""padding:0;Margin:0;padding-bottom:20px;font-size:0px""><img src=""https://eovwsew.stripocdn.email/content/guids/CABINET_df50fa2c91fe0787d6271ef7120d2b0a957d7315a7463eab633e367bb684105b/images/thootologo_1.png"" href=""https://thooto.com/#"" alt="""" width=""200"" title=""Logo"" class=""adapt-img"" style=""display:block;font-size:12px;border:0;outline:none;text-decoration:none""></td> </tr></table></td></tr></table></td></tr></table></td></tr></table> <table cellpadding=""0"" cellspacing=""0"" align=""center"" class=""es-content"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important""><tr>
<td align=""center"" style=""padding:0;Margin:0""><table bgcolor=""#ffffff"" align=""center"" cellpadding=""0"" cellspacing=""0"" class=""es-content-body"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FFFFFF;width:600px""><tr><td align=""left"" style=""Margin:0;padding-right:20px;padding-left:20px;padding-top:30px;padding-bottom:30px""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr><td align=""center"" valign=""top"" style=""padding:0;Margin:0;width:560px""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr>
<td align=""center"" style=""padding:0;Margin:0;padding-top:10px;padding-bottom:10px;font-size:0px""><img src=""https://eovwsew.stripocdn.email/content/guids/CABINET_67e080d830d87c17802bd9b4fe1c0912/images/55191618237638326.png"" href=""https://thooto.com/#"" alt="""" width=""100"" style=""display:block;font-size:14px;border:0;outline:none;text-decoration:none""></td> </tr><tr><td align=""center"" class=""es-m-txt-c"" style=""padding:0;Margin:0;padding-bottom:10px""><h1 style=""Margin:0;font-family:arial, 'helvetica neue', helvetica, sans-serif;mso-line-height-rule:exactly;letter-spacing:0;font-size:46px;font-style:normal;font-weight:bold;line-height:46px;color:#333333"">Confirm Your Email</h1></td></tr><tr>
<td align=""center"" class=""es-m-p0r es-m-p0l"" style=""Margin:0;padding-top:5px;padding-right:40px;padding-bottom:5px;padding-left:40px""><p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;letter-spacing:0;color:#333333;font-size:14px"">You’ve received this message because your email address has been registered with our site. Please use the OTP (One-Time Password) below to verify your email address and confirm that you are the owner of this account.</p> <p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;letter-spacing:0;color:#333333;font-size:14px""><strong>OTP: [Your OTP Here]</strong></p><p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;letter-spacing:0;color:#333333;font-size:14px""><strong>​</strong></p>
<p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;letter-spacing:0;color:#333333;font-size:14px""><strong>​</strong></p><p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;letter-spacing:0;color:#333333;font-size:14px"">If you did not request this, please ignore this message.</p></td></tr> <tr><td align=""center"" class=""es-m-p0r es-m-p0l"" style=""Margin:0;padding-top:5px;padding-right:40px;padding-bottom:5px;padding-left:40px""><p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;letter-spacing:0;color:#333333;font-size:14px"">Once confirmed, this email will be uniquely associated with your account.</p></td></tr></table></td></tr></table></td></tr></table></td></tr></table>
 <table cellpadding=""0"" cellspacing=""0"" align=""center"" class=""es-footer"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important;background-color:transparent;background-repeat:repeat;background-position:center top""><tr><td align=""center"" style=""padding:0;Margin:0""><table cellspacing=""0"" align=""center"" cellpadding=""0"" class=""es-footer-body"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:600px"" role=""none""><tr><td align=""left"" style=""Margin:0;padding-right:20px;padding-left:20px;padding-bottom:20px;padding-top:20px""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr>
<td align=""left"" style=""padding:0;Margin:0;width:560px""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr><td align=""center"" style=""padding:0;Margin:0;padding-top:15px;padding-bottom:15px;font-size:0""><table cellspacing=""0"" cellpadding=""0"" class=""es-table-not-adapt es-social"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr>
<td align=""center"" valign=""top"" style=""padding:0;Margin:0""><a href=""https://www.linkedin.com/company/thooto/posts/?feedView=all"" target=""_blank"" style=""mso-line-height-rule:exactly;text-decoration:underline;color:#333333;font-size:12px""><img alt=""In"" width=""32"" title=""LinkedIn"" src=""https://eovwsew.stripocdn.email/content/assets/img/social-icons/logo-black/linkedin-logo-black.png"" style=""display:block;font-size:14px;border:0;outline:none;text-decoration:none""></a> </td></tr></table></td></tr><tr><td align=""center"" style=""padding:0;Margin:0;padding-bottom:35px""><p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:18px;letter-spacing:0;color:#333333;font-size:12px"">thooto (2024). All Rights Reserved.</p>
<p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:18px;letter-spacing:0;color:#333333;font-size:12px"">Corner Tyrwhitt and 24 Cradock Ave, Rosebank, Johannesburg, 2196</p><p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:18px;letter-spacing:0;color:#333333;font-size:12px"">Call: +27 10 900 5173</p></td></tr> <tr><td style=""padding:0;Margin:0""><table cellspacing=""0"" width=""100%"" cellpadding=""0"" class=""es-menu"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr class=""links"">
<td align=""center"" valign=""top"" width=""33.33%"" style=""Margin:0;border:0;padding-top:5px;padding-bottom:5px;padding-right:5px;padding-left:5px""><a href=""https://thooto.com"" target=""_blank"" style=""mso-line-height-rule:exactly;text-decoration:none;font-family:arial, 'helvetica neue', helvetica, sans-serif;display:block;color:#999999;font-size:12px"">Visit Us </a></td> <td width=""33.33%"" align=""center"" valign=""top"" style=""Margin:0;border:0;padding-top:5px;padding-bottom:5px;padding-right:5px;padding-left:5px;border-left:1px solid #cccccc""><a target=""_blank"" href="""" style=""mso-line-height-rule:exactly;text-decoration:none;font-family:arial, 'helvetica neue', helvetica, sans-serif;display:block;color:#999999;font-size:12px"">Privacy Policy</a></td>
<td width=""33.33%"" align=""center"" valign=""top"" style=""Margin:0;border:0;padding-top:5px;padding-bottom:5px;padding-right:5px;padding-left:5px;border-left:1px solid #cccccc""><a target=""_blank"" href="""" style=""mso-line-height-rule:exactly;text-decoration:none;font-family:arial, 'helvetica neue', helvetica, sans-serif;display:block;color:#999999;font-size:12px"">Terms of Use</a></td></tr></table></td></tr></table></td></tr></table></td></tr></table></td></tr></table> <table cellpadding=""0"" cellspacing=""0"" align=""center"" class=""es-content"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important""><tr>
<td align=""center"" class=""es-info-area"" style=""padding:0;Margin:0""><table bgcolor=""#FFFFFF"" align=""center"" cellpadding=""0"" cellspacing=""0"" class=""es-content-body"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:600px"" role=""none""><tr><td align=""left"" style=""padding:20px;Margin:0""><table cellspacing=""0"" width=""100%"" cellpadding=""0"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr><td valign=""top"" align=""center"" style=""padding:0;Margin:0;width:560px""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr>
<td align=""center"" class=""es-infoblock"" style=""padding:0;Margin:0""><p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:18px;letter-spacing:0;color:#CCCCCC;font-size:12px""><a target=""_blank"" href="""" style=""mso-line-height-rule:exactly;text-decoration:underline;color:#CCCCCC;font-size:12px""></a>No longer want to receive these emails?&nbsp;<a href="""" target=""_blank"" style=""mso-line-height-rule:exactly;text-decoration:underline;color:#CCCCCC;font-size:12px"">Unsubscribe</a>.<a target=""_blank"" href="""" style=""mso-line-height-rule:exactly;text-decoration:underline;color:#CCCCCC;font-size:12px""></a></p> </td></tr></table></td></tr></table></td></tr></table></td></tr></table></td></tr></table></div></body></html>";


        }

        private string NotificationMessage()
        {
            return @"<!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.0 Transitional//EN"" ""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd""><html dir=""ltr"" xmlns=""http://www.w3.org/1999/xhtml"" xmlns:o=""urn:schemas-microsoft-com:office:office"" lang=""en""><head><meta charset=""UTF-8""><meta content=""width=device-width, initial-scale=1"" name=""viewport""><meta name=""x-apple-disable-message-reformatting""><meta http-equiv=""X-UA-Compatible"" content=""IE=edge""><meta content=""telephone=no"" name=""format-detection""><title>New Message 2</title> <!--[if (mso 16)]><style type=""text/css"">     a {text-decoration: none;}     </style><![endif]--> <!--[if gte mso 9]><style>sup { font-size: 100% !important; }</style><![endif]--> <!--[if gte mso 9]><noscript> <xml> <o:OfficeDocumentSettings> <o:AllowPNG></o:AllowPNG> <o:PixelsPerInch>96</o:PixelsPerInch> </o:OfficeDocumentSettings> </xml> </noscript>
<![endif]--><style type=""text/css"">.rollover:hover .rollover-first { max-height:0px!important; display:none!important;}.rollover:hover .rollover-second { max-height:none!important; display:block!important;}.rollover span { font-size:0px;}u + .body img ~ div div { display:none;}#outlook a { padding:0;}span.MsoHyperlink,span.MsoHyperlinkFollowed { color:inherit; mso-style-priority:99;}a.es-button { mso-style-priority:100!important; text-decoration:none!important;}a[x-apple-data-detectors],#MessageViewBody a { color:inherit!important; text-decoration:none!important; font-size:inherit!important; font-family:inherit!important; font-weight:inherit!important; line-height:inherit!important;}.es-desk-hidden { display:none; float:left; overflow:hidden; width:0; max-height:0; line-height:0; mso-hide:all;} @media only screen and (max-width:600px) {.es-m-p0r { padding-right:0px!important } .es-p-default { }
 *[class=""gmail-fix""] { display:none!important } p, a { line-height:150%!important } h1, h1 a { line-height:120%!important } h2, h2 a { line-height:120%!important } h3, h3 a { line-height:120%!important } h4, h4 a { line-height:120%!important } h5, h5 a { line-height:120%!important } h6, h6 a { line-height:120%!important } .es-header-body p { } .es-content-body p { } .es-footer-body p { } .es-infoblock p { } h1 { font-size:36px!important; text-align:left } h2 { font-size:26px!important; text-align:left } h3 { font-size:20px!important; text-align:left } h4 { font-size:24px!important; text-align:left } h5 { font-size:20px!important; text-align:left } h6 { font-size:16px!important; text-align:left } .es-header-body h1 a, .es-content-body h1 a, .es-footer-body h1 a { font-size:36px!important } .es-header-body h2 a, .es-content-body h2 a, .es-footer-body h2 a { font-size:26px!important }
 .es-header-body h3 a, .es-content-body h3 a, .es-footer-body h3 a { font-size:20px!important } .es-header-body h4 a, .es-content-body h4 a, .es-footer-body h4 a { font-size:24px!important } .es-header-body h5 a, .es-content-body h5 a, .es-footer-body h5 a { font-size:20px!important } .es-header-body h6 a, .es-content-body h6 a, .es-footer-body h6 a { font-size:16px!important } .es-menu td a { font-size:12px!important } .es-header-body p, .es-header-body a { font-size:14px!important } .es-content-body p, .es-content-body a { font-size:14px!important } .es-footer-body p, .es-footer-body a { font-size:14px!important } .es-infoblock p, .es-infoblock a { font-size:12px!important } .es-m-txt-c, .es-m-txt-c h1, .es-m-txt-c h2, .es-m-txt-c h3, .es-m-txt-c h4, .es-m-txt-c h5, .es-m-txt-c h6 { text-align:center!important }
 .es-m-txt-r, .es-m-txt-r h1, .es-m-txt-r h2, .es-m-txt-r h3, .es-m-txt-r h4, .es-m-txt-r h5, .es-m-txt-r h6 { text-align:right!important } .es-m-txt-j, .es-m-txt-j h1, .es-m-txt-j h2, .es-m-txt-j h3, .es-m-txt-j h4, .es-m-txt-j h5, .es-m-txt-j h6 { text-align:justify!important } .es-m-txt-l, .es-m-txt-l h1, .es-m-txt-l h2, .es-m-txt-l h3, .es-m-txt-l h4, .es-m-txt-l h5, .es-m-txt-l h6 { text-align:left!important } .es-m-txt-r img, .es-m-txt-c img, .es-m-txt-l img { display:inline!important } .es-m-txt-r .rollover:hover .rollover-second, .es-m-txt-c .rollover:hover .rollover-second, .es-m-txt-l .rollover:hover .rollover-second { display:inline!important } .es-m-txt-r .rollover span, .es-m-txt-c .rollover span, .es-m-txt-l .rollover span { line-height:0!important; font-size:0!important; display:block } .es-spacer { display:inline-table }
 a.es-button, button.es-button { font-size:20px!important; padding:10px 20px 10px 20px!important; line-height:120%!important } a.es-button, button.es-button, .es-button-border { display:inline-block!important } .es-m-fw, .es-m-fw.es-fw, .es-m-fw .es-button { display:block!important } .es-m-il, .es-m-il .es-button, .es-social, .es-social td, .es-menu { display:inline-block!important } .es-adaptive table, .es-left, .es-right { width:100%!important } .es-content table, .es-header table, .es-footer table, .es-content, .es-footer, .es-header { width:100%!important; max-width:600px!important } .adapt-img { width:100%!important; height:auto!important } .es-mobile-hidden, .es-hidden { display:none!important } .es-desk-hidden { width:auto!important; overflow:visible!important; float:none!important; max-height:inherit!important; line-height:inherit!important } tr.es-desk-hidden { display:table-row!important }
 table.es-desk-hidden { display:table!important } td.es-desk-menu-hidden { display:table-cell!important } .es-menu td { width:1%!important } table.es-table-not-adapt, .esd-block-html table { width:auto!important } .h-auto { height:auto!important } }@media screen and (max-width:384px) {.mail-message-content { width:414px!important } }</style>
 </head> <body class=""body"" style=""width:100%;height:100%;padding:0;Margin:0""><div dir=""ltr"" class=""es-wrapper-color"" lang=""en"" style=""background-color:#FAFAFA""> <!--[if gte mso 9]><v:background xmlns:v=""urn:schemas-microsoft-com:vml"" fill=""t""> <v:fill type=""tile"" color=""#fafafa""></v:fill> </v:background><![endif]--><table width=""100%"" cellspacing=""0"" cellpadding=""0"" class=""es-wrapper"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;padding:0;Margin:0;width:100%;height:100%;background-repeat:repeat;background-position:center top;background-color:#FAFAFA""><tr>
<td valign=""top"" style=""padding:0;Margin:0""><table cellpadding=""0"" cellspacing=""0"" align=""center"" class=""es-header"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important;background-color:transparent;background-repeat:repeat;background-position:center top""><tr><td align=""center"" style=""padding:0;Margin:0""><table bgcolor=""#ffffff"" align=""center"" cellpadding=""0"" cellspacing=""0"" class=""es-header-body"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:600px""><tr><td align=""left"" style=""Margin:0;padding-top:10px;padding-right:20px;padding-bottom:10px;padding-left:20px""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr>
<td valign=""top"" align=""center"" class=""es-m-p0r"" style=""padding:0;Margin:0;width:560px""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr><td align=""center"" style=""padding:0;Margin:0;padding-bottom:20px;font-size:0px""><img src=""https://eovwsew.stripocdn.email/content/guids/CABINET_01a3b21ebaa00abfcaf2f1678a33a1182b7105afe5bd44d98561066f5c8352e9/images/thootologo_1.png"" alt="""" width=""175"" title=""Logo"" class=""adapt-img"" style=""display:block;font-size:12px;border:0;outline:none;text-decoration:none""></td> </tr></table></td></tr></table></td></tr></table></td></tr></table> <table cellpadding=""0"" cellspacing=""0"" align=""center"" class=""es-content"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important""><tr>
<td align=""center"" style=""padding:0;Margin:0""><table bgcolor=""#ffffff"" align=""center"" cellpadding=""0"" cellspacing=""0"" class=""es-content-body"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FFFFFF;width:600px""><tr><td align=""left"" style=""padding:0;Margin:0;padding-right:20px;padding-left:20px;padding-top:15px""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr><td align=""center"" valign=""top"" style=""padding:0;Margin:0;width:560px""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr>
<td align=""center"" class=""es-m-txt-c"" style=""padding:0;Margin:0;padding-top:15px;padding-bottom:15px""><h2 style=""Margin:0;font-family:arial, 'helvetica neue', helvetica, sans-serif;mso-line-height-rule:exactly;letter-spacing:0;font-size:26px;font-style:normal;font-weight:bold;line-height:31.2px;color:#333333"">You have a new message</h2> </td></tr><tr><td align=""left"" style=""padding:0;Margin:0;padding-top:10px;padding-bottom:10px""><p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px""></p><p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;letter-spacing:0;color:#333333;font-size:14px""><strong>New Notification from Thooto platform</strong></p>
<p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;letter-spacing:0;color:#333333;font-size:14px"">You have a new notification. Please find the details below:</p><p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:24px;letter-spacing:0;color:#333333;font-size:16px""></p></td></tr></table></td> </tr></table></td></tr> <tr><td align=""left"" style=""padding:0;Margin:0;padding-right:20px;padding-bottom:10px;padding-left:20px""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr>
<td align=""center"" valign=""top"" style=""padding:0;Margin:0;width:560px""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:separate;border-spacing:0px;border-radius:5px"" role=""presentation""><tr><td align=""left"" style=""padding:0;Margin:0;padding-bottom:10px;padding-top:20px""><p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;letter-spacing:0;color:#333333;font-size:14px""><strong> </strong>[Content]</p>
 <p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;letter-spacing:0;color:#333333;font-size:14px"">​<strong> </strong></p><p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:21px;letter-spacing:0;color:#333333;font-size:14px"">Thanks,<br>The thooto Team</p></td></tr></table></td></tr></table></td></tr></table></td></tr></table> <table cellpadding=""0"" cellspacing=""0"" align=""center"" class=""es-footer"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important;background-color:transparent;background-repeat:repeat;background-position:center top""><tr>
<td align=""center"" style=""padding:0;Margin:0""><table cellspacing=""0"" align=""center"" cellpadding=""0"" class=""es-footer-body"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:600px"" role=""none""><tr><td align=""left"" style=""Margin:0;padding-right:20px;padding-left:20px;padding-bottom:20px;padding-top:20px""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr><td align=""left"" style=""padding:0;Margin:0;width:560px""><table cellspacing=""0"" width=""100%"" cellpadding=""0"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr>
<td align=""center"" style=""padding:0;Margin:0;padding-top:15px;padding-bottom:15px;font-size:0""><table cellpadding=""0"" cellspacing=""0"" class=""es-table-not-adapt es-social"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr><td align=""center"" valign=""top"" style=""padding:0;Margin:0;padding-right:40px""><a target=""_blank"" href=""https://www.linkedin.com/company/thooto/posts/?feedView=all"" style=""mso-line-height-rule:exactly;text-decoration:underline;color:#333333;font-size:12px""><img alt=""In"" width=""32"" height=""32"" title=""LinkedIn"" src=""https://eovwsew.stripocdn.email/content/assets/img/social-icons/logo-black/linkedin-logo-black.png"" style=""display:block;font-size:14px;border:0;outline:none;text-decoration:none""></a> </td></tr></table></td></tr><tr>
<td align=""center"" style=""padding:0;Margin:0;padding-bottom:35px""><p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:18px;letter-spacing:0;color:#333333;font-size:12px"">thooto (2024). All Rights Reserved.</p><p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:18px;letter-spacing:0;color:#333333;font-size:12px"">Corner Tyrwhitt and 24 Cradock Ave, Rosebank, Johannesburg, 2196</p><p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:18px;letter-spacing:0;color:#333333;font-size:12px"">Call: +27 10 900 5173</p></td></tr> <tr>
<td style=""padding:0;Margin:0""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" class=""es-menu"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr class=""links""><td width=""33.33%"" align=""center"" valign=""top"" style=""Margin:0;border:0;padding-top:5px;padding-bottom:5px;padding-right:5px;padding-left:5px""><a target=""_blank"" href=""https://thooto.com"" style=""mso-line-height-rule:exactly;text-decoration:none;font-family:arial, 'helvetica neue', helvetica, sans-serif;display:block;color:#999999;font-size:12px"">Visit Us </a></td>
 <td align=""center"" valign=""top"" width=""33.33%"" style=""Margin:0;border:0;padding-top:5px;padding-bottom:5px;padding-right:5px;padding-left:5px;border-left:1px solid #cccccc""><a target=""_blank"" href="""" style=""mso-line-height-rule:exactly;text-decoration:none;font-family:arial, 'helvetica neue', helvetica, sans-serif;display:block;color:#999999;font-size:12px"">Privacy Policy</a></td><td align=""center"" valign=""top"" width=""33.33%"" style=""Margin:0;border:0;padding-top:5px;padding-bottom:5px;padding-right:5px;padding-left:5px;border-left:1px solid #cccccc""><a target=""_blank"" href="""" style=""mso-line-height-rule:exactly;text-decoration:none;font-family:arial, 'helvetica neue', helvetica, sans-serif;display:block;color:#999999;font-size:12px"">Terms of Use</a></td></tr></table></td></tr></table></td></tr></table></td></tr></table></td></tr></table>
 <table cellpadding=""0"" cellspacing=""0"" align=""center"" class=""es-content"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;width:100%;table-layout:fixed !important""><tr><td align=""center"" class=""es-info-area"" style=""padding:0;Margin:0""><table bgcolor=""#FFFFFF"" align=""center"" cellpadding=""0"" cellspacing=""0"" class=""es-content-body"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:transparent;width:600px"" role=""none""><tr><td align=""left"" style=""padding:20px;Margin:0""><table width=""100%"" cellpadding=""0"" cellspacing=""0"" role=""none"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr>
<td align=""center"" valign=""top"" style=""padding:0;Margin:0;width:560px""><table cellpadding=""0"" cellspacing=""0"" width=""100%"" role=""presentation"" style=""mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px""><tr><td align=""center"" class=""es-infoblock"" style=""padding:0;Margin:0""><p style=""Margin:0;mso-line-height-rule:exactly;font-family:arial, 'helvetica neue', helvetica, sans-serif;line-height:18px;letter-spacing:0;color:#CCCCCC;font-size:12px""><a target=""_blank"" href="""" style=""mso-line-height-rule:exactly;text-decoration:underline;color:#CCCCCC;font-size:12px""></a>No longer want to receive these emails?&nbsp;<a href="""" target=""_blank"" style=""mso-line-height-rule:exactly;text-decoration:underline;color:#CCCCCC;font-size:12px"">Unsubscribe</a>.<a target=""_blank"" href="""" style=""mso-line-height-rule:exactly;text-decoration:underline;color:#CCCCCC;font-size:12px""></a></p> </td></tr></table></td></tr></table>
</td></tr></table></td></tr></table></td></tr></table></div></body></html>";
        }

        private string LoginDetailsEmail()
        {
            return
                   @"<!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.0 Transitional//EN"" ""http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"">
<html dir=""ltr"" xmlns=""http://www.w3.org/1999/xhtml"" xmlns:o=""urn:schemas-microsoft-com:office:office"" lang=""en"">
<head>
    <meta charset=""UTF-8"">
    <meta content=""width=device-width, initial-scale=1"" name=""viewport"">
    <meta name=""x-apple-disable-message-reformatting"">
    <meta http-equiv=""X-UA-Compatible"" content=""IE=edge"">
    <meta content=""telephone=no"" name=""format-detection"">
    <title>Welcome to Thooto</title>
</head>
<body style=""width:100%;height:100%;padding:0;margin:0;background-color:#f4f4f4;font-family:Arial,sans-serif;"">
    <div style=""width:100%;max-width:600px;margin:0 auto;background-color:#ffffff;padding:20px;box-shadow:0 0 10px rgba(0,0,0,0.1);"">
        //<div style=""text-align:center;padding:20px 0;"">
        //    <img src=""https://eovwsew.stripocdn.email/content/guids/CABINET_01a3b21ebaa00abfcaf2f1678a33a1182b7105afe5bd44d98561066f5c8352e9/images/thootologo_1.png"" alt=""Thooto Logo"" style=""width:150px;"">
        //</div>
        <div style=""padding:20px;"">
            <h1 style=""font-size:24px;color:#333333;"">Welcome to Thooto!</h1>
            <p style=""font-size:16px;color:#666666;line-height:1.5;"">Dear [Name],</p>
            <p style=""font-size:16px;color:#666666;line-height:1.5;"">We are excited to welcome you to Thooto. Below are your login details:</p>
            <p style=""font-size:16px;color:#666666;line-height:1.5;""><strong>Email:</strong> [UserEmail]</p>
            <p style=""font-size:16px;color:#666666;line-height:1.5;""><strong>Password:</strong> [UserPassword]</p>
            <p style=""font-size:16px;color:#666666;line-height:1.5;""><strong>Role:</strong> [UserRole]</p>
            <p style=""font-size:16px;color:#666666;line-height:1.5;"">Please log in to your account and change your password as soon as possible.</p>
            <p style=""font-size:16px;color:#666666;line-height:1.5;"">We are here to support you every step of the way. If you have any questions, feel free to reach out to us.</p>
            <p style=""font-size:16px;color:#666666;line-height:1.5;"">Best regards,<br>The Thooto Team</p>
        </div>
        <div style=""text-align:center;padding:20px;font-size:12px;color:#999999;"">
            <p style=""margin:0;"">Got a question? Email us at <a href=""mailto:account@fraktionaldev.com"" style=""color:#5C68E2;text-decoration:none;"">account@fraktionaldev.com</a> or give us a call at +27 10 900 5173.</p>
            <p style=""margin:0;"">Thooto (2024). All Rights Reserved.</p>
            <p style=""margin:0;"">Corner Tyrwhitt and 24 Cradock Ave, Rosebank, Johannesburg, 2196</p>
            <p style=""margin:0;"">Call: +27 10 900 5173</p>
            <p style=""margin:0;""><a href=""https://thooto.com"" style=""color:#5C68E2;text-decoration:none;"">Visit Us</a> | <a href=""#"" style=""color:#5C68E2;text-decoration:none;"">Privacy Policy</a> | <a href=""#"" style=""color:#5C68E2;text-decoration:none;"">Terms of Use</a></p>
        </div>
    </div>
</body>
</html>";
        }

    }
}
